BEGIN
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SALES_CHANNEL_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SALES_CHANNEL_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SALES_CHANNEL_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SALES_CHANNEL_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SAVESTATS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SAVESTATS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SDP_PARAMETERS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SDP_PARAMETERS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SDR_EXCHANGE_RATES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SDR_EXCHANGE_RATES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SEGMENTATION_KEY_ATTR_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SEGMENTATION_KEY_ATTR_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SEGMENTATION_KEY_ATTR_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SEGMENTATION_KEY_ATTR_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SEGMENTATION_KEY_ATTR_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SEGMENTATION_KEY_ATTR_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SEGMENTATION_KEY_ATTR_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SEGMENTATION_KEY_ATTR_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SEGMENTATION_KEY_ID_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SEGMENTATION_KEY_ID_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SEGMENTATION_KEY_ID_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SEGMENTATION_KEY_ID_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SEGMENTATION_KEY_ID_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SEGMENTATION_KEY_ID_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SEQ_NUM', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SEQ_NUM');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVER_CATEGORY_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVER_CATEGORY_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVER_CATEGORY_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVER_CATEGORY_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVER_DEFINITION', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVER_DEFINITION');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICEABILITY_ATTRIBUTE_DEF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICEABILITY_ATTRIBUTE_DEF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_CATEGORY_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_CATEGORY_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_CATEGORY_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_CATEGORY_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_CATEGORY_SVBL_ATTR_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_CATEGORY_SVBL_ATTR_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_CATEGORY_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_CATEGORY_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_CENTERS', statid => 'STATS2013');
exec dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_CENTERS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_CENTER_TYPES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_CENTER_TYPES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_CENTER_TYPE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_CENTER_TYPE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_CENTER_TYPE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_CENTER_TYPE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_ITEM_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_ITEM_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_ITEM_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_ITEM_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_ITEM_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_ITEM_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_PLAN_ITEM_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_PLAN_ITEM_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_PLAN_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_PLAN_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_PLAN_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_PLAN_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_PLAN_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_PLAN_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_PROVIDERS_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_PROVIDERS_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_PROVIDERS_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_PROVIDERS_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_PROVIDERS_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_PROVIDERS_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_PROVIDER_OPEN_ITEM_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_PROVIDER_OPEN_ITEM_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_VERSION', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_VERSION');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SERVICE_VERSION_CHG_LOG', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SERVICE_VERSION_CHG_LOG');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SIN_GROUPS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SIN_GROUPS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SIN_GROUP_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SIN_GROUP_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SIN_GROUP_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SIN_GROUP_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SIN_INCOMPLETE', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SIN_INCOMPLETE');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SIN_INVOICE_TEMP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SIN_INVOICE_TEMP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SIN_SEQ_NO', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SIN_SEQ_NO');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_ADJ', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_ADJ');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_ADJ_BALANCE', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_ADJ_BALANCE');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_ADJ_TAX', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_ADJ_TAX');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_CHARGE_UNBILLED', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_CHARGE_UNBILLED');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_CMF_INTERIM_BILLS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_CMF_INTERIM_BILLS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_MTR', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_MTR');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_NRC', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_NRC');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_NRC_BALANCE', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_NRC_BALANCE');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_NRC_TAX', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_NRC_TAX');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_NRC_TERM_INST', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_NRC_TERM_INST');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_OFFER_INST_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_OFFER_INST_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_RC', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_RC');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_RC_BALANCE', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_RC_BALANCE');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_RC_TAX', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_RC_TAX');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_RC_TERM_INST', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_RC_TERM_INST');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGED_UPDATEBALANCE_ADJ', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGED_UPDATEBALANCE_ADJ');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGING_CONTROL_ENTITY_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGING_CONTROL_ENTITY_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STAGING_CONTROL_MASTER', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STAGING_CONTROL_MASTER');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STATE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STATE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STATE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STATE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STATS_CBS_OWNER', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STATS_CBS_OWNER');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STATUS_REASON_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STATUS_REASON_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STATUS_REASON_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STATUS_REASON_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STATUS_REASON_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STATUS_REASON_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STATUS_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STATUS_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STATUS_TYPE_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STATUS_TYPE_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STATUS_TYPE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STATUS_TYPE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STATUS_TYPE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STATUS_TYPE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'STATUS_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'STATUS_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSCRIBER_ADDRESS_ASSOC', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSCRIBER_ADDRESS_ASSOC');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSCRIBER_BILLING', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSCRIBER_BILLING');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSCRIBER_EXT', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSCRIBER_EXT');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSCRIBER_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSCRIBER_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSCRIBER_STATE_ID_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSCRIBER_STATE_ID_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSCRIBER_STATE_ID_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSCRIBER_STATE_ID_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSCRIBER_STATUS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSCRIBER_STATUS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSCRIBER_VIEW', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSCRIBER_VIEW');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSCRIBER_ZONE', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSCRIBER_ZONE');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSCR_ACCU_RESET', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSCR_ACCU_RESET');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSYSTEM_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSYSTEM_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSYSTEM_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSYSTEM_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBSYSTEM_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBSYSTEM_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUBS_PARAMETER', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUBS_PARAMETER');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUB_TYPE_ID_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUB_TYPE_ID_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUB_TYPE_ID_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUB_TYPE_ID_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUB_TYPE_ID_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUB_TYPE_ID_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUSPENDED_REASON_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUSPENDED_REASON_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SUSPENDED_REASON_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SUSPENDED_REASON_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SYSTEM_MESSAGES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SYSTEM_MESSAGES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SYSTEM_MODULES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SYSTEM_MODULES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'SYSTEM_PARAMETERS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'SYSTEM_PARAMETERS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAP_GSM_PROVIDER_ID_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAP_GSM_PROVIDER_ID_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAP_GSM_PROVIDER_ID_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAP_GSM_PROVIDER_ID_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAP_MAPPING', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAP_MAPPING');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TARIFF_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TARIFF_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TARIFF_PLAN_GSM_PROVIDER', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TARIFF_PLAN_GSM_PROVIDER');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TARIFF_PLAN_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TARIFF_PLAN_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TARIFF_PLAN_MAPPING', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TARIFF_PLAN_MAPPING');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TARIFF_PLAN_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TARIFF_PLAN_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TARIFF_PLAN_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TARIFF_PLAN_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TARIFF_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TARIFF_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TARIFF_SET_ID_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TARIFF_SET_ID_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TARIFF_SET_ID_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TARIFF_SET_ID_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TARIFF_SET_ID_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TARIFF_SET_ID_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TARIFF_SET_MEMBER', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TARIFF_SET_MEMBER');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TARIFF_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TARIFF_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_ASSIGNMENTS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_ASSIGNMENTS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_CHARGE_ELEMENTS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_CHARGE_ELEMENTS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_CLASS_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_CLASS_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_CLASS_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_CLASS_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_CLASS_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_CLASS_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_CODES_COMM', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_CODES_COMM');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_ELEM_DEFAULT_LOC', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_ELEM_DEFAULT_LOC');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_OVERRIDES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_OVERRIDES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_PKG_INST_ID_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_PKG_INST_ID_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_PKG_INST_ID_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_PKG_INST_ID_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_PKG_INST_ID_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_PKG_INST_ID_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_RATES_VAT', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_RATES_VAT');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_STATUS_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_STATUS_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_STATUS_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_STATUS_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_STATUS_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_STATUS_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_THRESHOLDS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_THRESHOLDS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_THRESHOLD_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_THRESHOLD_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_THRESHOLD_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_THRESHOLD_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_THRESHOLD_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_THRESHOLD_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_TYPE_CODE_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_TYPE_CODE_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_TYPE_CODE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_TYPE_CODE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_TYPE_CODE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_TYPE_CODE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_TYPE_COMM_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_TYPE_COMM_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_TYPE_COMM_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_TYPE_COMM_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TAX_TYPE_COMM_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TAX_TYPE_COMM_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TIMEZONE_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TIMEZONE_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TIMEZONE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TIMEZONE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TIMEZONE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TIMEZONE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TIME_SLOT_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TIME_SLOT_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TIME_SLOT_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TIME_SLOT_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TIME_SLOT_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TIME_SLOT_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TIME_TYPES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TIME_TYPES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TIME_TYPE_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TIME_TYPE_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TIME_TYPE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TIME_TYPE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TIME_TYPE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TIME_TYPE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TML_DEFAULT_LIMIT', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TML_DEFAULT_LIMIT');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TRANSITION_RULE_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TRANSITION_RULE_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TRANSITION_RULE_MEMBER_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TRANSITION_RULE_MEMBER_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TRANSITION_RULE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TRANSITION_RULE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TRANSITION_RULE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TRANSITION_RULE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TRANSLATION', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TRANSLATION');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TRANS_SOURCE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TRANS_SOURCE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TRANS_SOURCE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TRANS_SOURCE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TSS_TRANSACTION', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TSS_TRANSACTION');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TSS_TRANSACTION_ERROR', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TSS_TRANSACTION_ERROR');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TSS_TRANSACTION_HIST', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TSS_TRANSACTION_HIST');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_PRIORITY_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_PRIORITY_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_PRIORITY_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_PRIORITY_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_SOURCE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_SOURCE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_SOURCE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_SOURCE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_STATUS_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_STATUS_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_STATUS_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_STATUS_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_SUB_TYPE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_SUB_TYPE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_SUB_TYPE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_SUB_TYPE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_SUB_TYPE_WP_PROCESS_ID_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_SUB_TYPE_WP_PROCESS_ID_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_TROUBLE_TICKET', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_TROUBLE_TICKET');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_TYPE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_TYPE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_TYPE_SUB_TYPE_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_TYPE_SUB_TYPE_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'TT_TYPE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'TT_TYPE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UI_CHARGE_DISPLAY_FORMAT', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UI_CHARGE_DISPLAY_FORMAT');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UNITS_TYPE_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UNITS_TYPE_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UNITS_TYPE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UNITS_TYPE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UNITS_TYPE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UNITS_TYPE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UNIT_CR_ITEM_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UNIT_CR_ITEM_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UNIT_CR_ITEM_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UNIT_CR_ITEM_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UNIT_CR_ITEM_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UNIT_CR_ITEM_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UNIT_CR_RATE_LIMIT', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UNIT_CR_RATE_LIMIT');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UNIT_CR_RATE_LIMIT_KEYS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UNIT_CR_RATE_LIMIT_KEYS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UNIT_CR_RESTRICTIONS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UNIT_CR_RESTRICTIONS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UNPAID_INVOICES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UNPAID_INVOICES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UNTRANSFERRED_DATA_DATE', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UNTRANSFERRED_DATA_DATE');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UP1', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UP1');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UP2', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UP2');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UPSELL_TEMPLATE_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UPSELL_TEMPLATE_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UPSELL_TEMPLATE_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UPSELL_TEMPLATE_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UPSELL_TEMPLATE_PRIORITY_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UPSELL_TEMPLATE_PRIORITY_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UPSELL_TEMPLATE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UPSELL_TEMPLATE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UPSELL_TEMPLATE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UPSELL_TEMPLATE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'URC_ACCT', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'URC_ACCT');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'URC_CDR', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'URC_CDR');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'URC_CDR_B', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'URC_CDR_B');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'URC_CDR_SP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'URC_CDR_SP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'URC_CDR_SPLIT', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'URC_CDR_SPLIT');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'URC_SUBSCR', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'URC_SUBSCR');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'URC_SUBSCR_SP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'URC_SUBSCR_SP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_CATEGORY_ID_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_CATEGORY_ID_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_CATEGORY_ID_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_CATEGORY_ID_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_CATEGORY_ID_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_CATEGORY_ID_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_CATEGORY_MEMBER', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_CATEGORY_MEMBER');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_FILES_TO_PROCESS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_FILES_TO_PROCESS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_FILE_CLASS_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_FILE_CLASS_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_FILE_CLASS_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_FILE_CLASS_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_FILE_PROCESS_STATE', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_FILE_PROCESS_STATE');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_ITEM_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_ITEM_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_ITEM_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_ITEM_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_ITEM_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_ITEM_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_JURISDICTION', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_JURISDICTION');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_LOCAL_COUNTS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_LOCAL_COUNTS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_LOCAL_ROLLUP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_LOCAL_ROLLUP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_MASTER_FILE_STATUS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_MASTER_FILE_STATUS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_PLAN_ITEM_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_PLAN_ITEM_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_PLAN_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_PLAN_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_PLAN_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_PLAN_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_PLAN_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_PLAN_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_POINTS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_POINTS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_POINTS_TEXT', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_POINTS_TEXT');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_PROCESS_FILE_STATUS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_PROCESS_FILE_STATUS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_TYPES_UNITS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_TYPES_UNITS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_UNITS_CONVERT', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_UNITS_CONVERT');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USAGE_UNITS_FORMATS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USAGE_UNITS_FORMATS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USSD_RESPONSE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USSD_RESPONSE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'USSD_RESPONSE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'USSD_RESPONSE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'UTL_TASK_STATUS', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'UTL_TASK_STATUS');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'VANITY_CODE_NRC_TERM_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'VANITY_CODE_NRC_TERM_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'VANITY_CODE_RC_TERM_MAP', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'VANITY_CODE_RC_TERM_MAP');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'VIP_CODE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'VIP_CODE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'VIP_CODE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'VIP_CODE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'VOUCHER_CARD', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'VOUCHER_CARD');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'WKRD_FREE_MINUTES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'WKRD_FREE_MINUTES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'WO_WORKORDER', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'WO_WORKORDER');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'WO_WORKORDER_ITEM', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'WO_WORKORDER_ITEM');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'WO_WORKORDER_ITEM_TYPE_DEF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'WO_WORKORDER_ITEM_TYPE_DEF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'WO_WORKORDER_TYPE_DEF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'WO_WORKORDER_TYPE_DEF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'WO_WORKORDER_TYPE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'WO_WORKORDER_TYPE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'WO_WORKORDER_TYPE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'WO_WORKORDER_TYPE_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'ZIPCODE', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'ZIPCODE');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'ZONE_CLASS_KEY', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'ZONE_CLASS_KEY');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'ZONE_CLASS_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'ZONE_CLASS_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'ZONE_CLASS_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'ZONE_CLASS_VALUES');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'ZONE_REF', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'ZONE_REF');
dbms_stats.export_table_stats ( ownname => user , stattab => 'STATS_CBS_OWNER', tabname => 'ZONE_VALUES', statid => 'STATS2013');
dbms_stats.gather_table_stats('CBS_OWNER', 'ZONE_VALUES');

END;
